FROM ubuntu:14.04
MAINTAINER Cat.1 zhuyuefeng0@gmail.com

ENV FLASH_DATA=2018_12_17

RUN apt update && apt install -y python3-pip && apt-get clean
RUN pip3 install freeFile

RUN mkdir -p /webShell/ && cd /webShell

COPY ./ttyd_linux.x86_64 / 

RUN chmod +x ./ttyd_linux.x86_64 && cp ./ttyd_linux.x86_64 /usr/bin/

WORKDIR /

CMD ttyd_linux.x86_64 -p 1588 bash -x
